/* Generated By:JavaCC: Do not edit this line. QuartzConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuartzConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int THEN = 4;
  /** RegularExpression Id. */
  int ELSE = 5;
  /** RegularExpression Id. */
  int WHILE = 6;
  /** RegularExpression Id. */
  int FOR = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int DEF = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int FUN = 13;
  /** RegularExpression Id. */
  int PUTS = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"in\"",
    "\"do\"",
    "\"end\"",
    "\"def\"",
    "\"class\"",
    "\"fun\"",
    "\"puts\"",
    "<INTEGER>",
    "<STRING>",
    "<IDENTIFIER>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
  };

}
